default:
  data:
    data:
      type: ADNI2
      batch_size: 32
      random_seed: 42
      cache_mode: load
      normalize: true
      transpose: true
      pad_features: false
      truncate_features: false
      flatten: false
      timepoints_as_samples: false
      fc_input: false
      preserve_timepoints: false

    # filter:
    #   apply_demean: true
    #   apply_detrend: true
    #   apply_finalDetrend: false
    #   fhi: 0.08
    #   flp: 0.01
    #   k: 2
    #   remove_artifacts: true
    #   tr: 3000
    #   type: BandPassFilter
  model:
    freeze_encoder: false
    reset_decoder: false
  training:
    num_epochs: 1000
    save_dir: ./models
    evaluation_scope: combined
    vectorize_val_reference: false
    learning_rate: 1e-3
    weight_decay: 1e-4
    loss_params:
      pred_heads_delta: 1
      loss_per_feature: true
      swfcd_beta: 0
      swfcd_window: 30
      swfcd_step: 3
    convergence_patience: 10
    convergence_min_delta: 1e-4
    convergence_warmup_epochs: 10
    reproducibility:
      benchmark: false
      deterministic: true
      enabled: true
      seed: 42
      warn_only: false


LAE_400:
  static_params:
    data:
      data:
        parcelations: 400
        cache_file: data/ADNI_preprocessed_cache_400.pt
    model:
      name: LAE
      latent_dim: 32
  exp_params:
    training:
      reproducibility:
        seed: [42, 100, 1, 111, 1007, 751, 149, 1216, 67, 1717]

LAE_100:
  static_params:
    data:
      data:
        parcelations: 100
        cache_file: data/ADNI_preprocessed_cache_100.pt
    model:
      name: LAE
      latent_dim: 32
  exp_params:
    training:
      reproducibility:
        seed: [42, 100, 1, 111, 1007, 751, 149, 1216, 67, 1717]


VAE_400:
  static_params:
    data:
      data:
        parcelations: 400
        cache_file: data/ADNI_preprocessed_cache_400.pt
    model:
      name: VAE
      latent_dim: 8
      hidden_dims: [32]
    training:
      loss_params:
        beta: 1
  exp_params:
    training:
      reproducibility:
        seed: [42, 100, 1, 111, 1007, 751, 149, 1216, 67, 1717]

VAE_100:
  static_params:
    data:
      data:
        parcelations: 100
        cache_file: data/ADNI_preprocessed_cache_100.pt
    model:
      name: VAE
      latent_dim: 8
      hidden_dims: [32]
    training:
      loss_params:
        beta: 1
  exp_params:
    training:
      reproducibility:
        seed: [42, 100, 1, 111, 1007, 751, 149, 1216, 67, 1717]


ConvAE_400:
  static_params:
    data:
      data:
        parcelations: 400
        cache_file: data/ADNI_preprocessed_cache_400.pt
    model:
      name: ConvAE
      latent_dim: 32
      hidden_dims: [16]
      kernel_size: 3
    training:
      reproducibility:
        deterministic: false
  exp_params:
    training:
      reproducibility:
        seed: [42, 100, 1, 111, 1007, 751, 149, 1216, 67, 1717]

ConvAE_100:
  static_params:
    data:
      data:
        parcelations: 100
        cache_file: data/ADNI_preprocessed_cache_100.pt
    model:
      name: ConvAE
      latent_dim: 32
      hidden_dims: [16]
      kernel_size: 3
    training:
      reproducibility:
        deterministic: false
  exp_params:
    training:
      reproducibility:
        seed: [42, 100, 1, 111, 1007, 751, 149, 1216, 67, 1717]


ConvVAE_400:
  static_params:
    data:
      data:
        parcelations: 400
        cache_file: data/ADNI_preprocessed_cache_400.pt
    model:
      name: ConvVAE
      latent_dim: 32
      hidden_dims: [32, 16]
      kernel_size: 3
    training:
      reproducibility:
        deterministic: false
      loss_params:
        beta: 1.0
  exp_params:
    training:
      reproducibility:
        seed: [42, 100, 1, 111, 1007, 751, 149, 1216, 67, 1717]

ConvVAE_100:
  static_params:
    data:
      data:
        parcelations: 100
        cache_file: data/ADNI_preprocessed_cache_100.pt
    model:
      name: ConvVAE
      latent_dim: 32
      hidden_dims: [32, 16]
      kernel_size: 3
    training:
      reproducibility:
        deterministic: false
      loss_params:
        beta: 1.0
  exp_params:
    training:
      reproducibility:
        seed: [42, 100, 1, 111, 1007, 751, 149, 1216, 67, 1717]