default:
  data:
    data:
      batch_size: 32
      groups: [HC, MCI, AD]
      random_seed: 42
      datasplit_file: data/train_val_test_split.csv
      datasplit_mode: load
      normalize: true
      transpose: false
      pad_features: false
      truncate_features: false
      flatten: true
      timepoints_as_samples: false
      fc_input: false
      preserve_timepoints: true

    filter:
      apply_demean: true
      apply_detrend: true
      apply_finalDetrend: false
      fhi: 0.08
      flp: 0.01
      k: 2
      remove_artifacts: true
      tr: 3000
      type: BandPassFilter
  model:
    freeze_encoder: false
    reset_decoder: false
  training:
    num_epochs: 30
    save_dir: ./models
    learning_rate: 1e-3
    weight_decay: 1e-4
    loss_params:
      loss_per_feature: true
      swfcd_beta: 0
      swfcd_window: 30
      swfcd_step: 3
    convergence_patience: 10
    convergence_min_delta: 1e-4
    convergence_warmup_epochs: 10

LinearAE:
  static_params:
    model:
      name: LinearAE
  exp_params:
    model:
      latent_dim: [4, 8, 12]
    training:
      loss_params:
        beta: [1.0, 0.5, 0]
        swfcd_beta: [1.0, 0.5, 0]

BasicVAE:
  static_params:
    model:
      name: BasicVAE
    data:
      data:
        flatten: true
  exp_params:
    model:
      hidden_dims: [[6304, 3152], [6304], [3152]]
      latent_dim: [10, 8, 4]
    training:
      loss_params:
        beta: [1.0, 0.5, 0]
        swfcd_beta: [1.0, 0.5, 0]


BasicVAETimeShared:
  static_params:
    model:
      name: BasicVAETimeShared
    data:
      data:
        flatten: true
  exp_params:
    model:
      hidden_dims: [[256, 128], [128, 64], [128], [64]]
      latent_dim: [10, 8, 4, 2]
    training:
      loss_params:
        beta: [1.0, 0.5, 0]
        swfcd_beta: [1.0, 0.5, 0]

AutoencoderKL:
  static_params:
    data:
      data:
        pad_features: true
        flatten: false
    model:
      name: AutoencoderKLv3
    training:
      num_epochs: 120
      loss_params:
        beta: 0.5
        swfcd_beta: 0.5
  exp_params:
    model:
      latent_dim: [4, 8, 16]
      hidden_dims: [[64, 64, 64], [32, 32, 32]]
      num_res_blocks: [[1,1,1], [2,2,2], [3,3,3]]
      attention_levels: [[false, false, false], [false, false, true], [false, true, true]]
      with_encoder_nonlocal_attn: [false, true]
      with_decoder_nonlocal_attn: [false, true]


BasicConvAE:
  static_params:
    data:
      data:
        pad_features: true
        flatten: false
    model:
      name: BasicConvAE
    training:
      num_epochs: 120
  exp_params:
    model:
      hidden_dims: [[64], [32], [64,32], [128], [128,64],[128,64,32]]
      latent_dim: [16, 8, 4]
    training:
      loss_params:
        swfcd_beta: [0, 0.5]