default:
  data:
    data:
      type: ADNI
      batch_size: 32
      random_seed: 42
      cache_mode: none
      normalize: true
      transpose: true
      pad_features: false
      truncate_features: false
      flatten: false
      timepoints_as_samples: false
      fc_input: false
      preserve_timepoints: false
    filter:
      apply_demean: true
      apply_detrend: true
      apply_finalDetrend: false
      k: 2
      remove_artifacts: true
      tr: 3000
      type: BandPassFilter
  model:
    name: LAE
  training:
    num_epochs: 1000
    save_dir: ./models
    evaluation_scope: combined
    pipeline: standard
    vectorize_val_reference: false
    learning_rate: 1e-3
    weight_decay: 1e-4
    loss_params:
      pred_heads_delta: 1
      loss_per_feature: true
      swfcd_beta: 0
      swfcd_window: 30
      swfcd_step: 3
    convergence_patience: 10
    convergence_min_delta: 1e-4
    convergence_warmup_epochs: 10
    reproducibility:
      benchmark: false
      deterministic: true
      enabled: true
      seed: 42
      warn_only: false

LAE:
  static_params:
    model:
      name: LAE
      latent_dim: 32
  exp_params:
    data:
      filter:
        fhi: [0.001, 0.008, 0.01]
        flp: [0.08, 0.1, 0.01]
    training:
      reproducibility:
        seed: [42, 100, 1, 111, 1007, 751, 149, 1216, 67, 1717]
  
